In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math 
import copy 
import sys
from tkinter import *
from tkinter import ttk
from PIL import Image, ImageTk

%matplotlib inline 

In [2]:
df_train = pd.read_csv('KDDTrain+aggregate.csv')
df_train.head()

duration  protocol_type   service  flag   src_bytes   dst_bytes   land  \
0         0            tcp  ftp_data    SF         491           0      0   
1         0            udp     other    SF         146           0      0   
2         0            tcp   private    S0           0           0      0   
3         0            tcp      http    SF         232        8153      0   
4         0            tcp      http    SF         199         420      0   

    wrong_fragment   urgent   hot  ...   dst_host_srv_count  \
0                0        0     0  ...                   25   
1                0        0     0  ...                    1   
2                0        0     0  ...                   26   
3                0        0     0  ...                  255   
4                0        0     0  ...                  255   

    dst_host_same_srv_rate   dst_host_diff_srv_rate  \
0                     0.17                     0.03   
1                     0.00                     0.60   
2                     0.10                     0.05   
3                     1.00                     0.00   
4                     1.00                     0.00   

    dst_host_same_src_port_rate   dst_host_srv_diff_host_rate  \
0                          0.17                          0.00   
1                          0.88                          0.00   
2                          0.00                          0.00   
3                          0.03                          0.04   
4                          0.00                          0.00   

    dst_host_serror_rate    dst_host_srv_serror_rate   dst_host_rerror_rate  \
0                   0.00                        0.00                   0.05   
1                   0.00                        0.00                   0.00   
2                   1.00                        1.00                   0.00   
3                   0.03                        0.01                   0.00   
4                   0.00                        0.00                   0.00   

    dst_host_srv_rerror_rate   classification.  
0                       0.00            normal  
1                       0.00            normal  
2                       0.00               Dos  
3                       0.01            normal  
4                       0.00            normal  

[5 rows x 42 columns]

In [3]:
df_train.columns

Index(['duration', ' protocol_type', ' service', ' flag', ' src_bytes',
       ' dst_bytes', ' land', ' wrong_fragment', ' urgent', ' hot',
       ' num_failed_loginsì', ' logged_in', ' num_compromised', ' root_shell',
       ' su_attempted', ' num_root', ' num_file_creations', ' num_shells',
       ' num_access_files', ' num_outbound_cmds', ' is_host_login',
       ' is_guest_login', ' count', ' srv_count', ' serror_rate',
       ' srv_serror_rate', ' rerror_rate', ' srv_rerror_rate',
       ' same_srv_rate', ' diff_srv_rate', ' srv_diff_host_rate',
       ' dst_host_count', ' dst_host_srv_count', ' dst_host_same_srv_rate',
       ' dst_host_diff_srv_rate', ' dst_host_same_src_port_rate',
       ' dst_host_srv_diff_host_rate', ' dst_host_serror_rate',
       '  dst_host_srv_serror_rate', ' dst_host_rerror_rate',
       ' dst_host_srv_rerror_rate', ' classification.'],
      dtype='object')

In [4]:
df_test = pd.read_csv('KDDTest+aggregate.csv')
df_test.head()

duration  protocol_type   service  flag   src_bytes   dst_bytes   land  \
0         0            tcp   private   REJ           0           0      0   
1         0            tcp   private   REJ           0           0      0   
2         2            tcp  ftp_data    SF       12983           0      0   
3         0           icmp     eco_i    SF          20           0      0   
4         1            tcp    telnet  RSTO           0          15      0   

    wrong_fragment   urgent   hot  ...   dst_host_srv_count  \
0                0        0     0  ...                   10   
1                0        0     0  ...                    1   
2                0        0     0  ...                   86   
3                0        0     0  ...                   57   
4                0        0     0  ...                   86   

    dst_host_same_srv_rate   dst_host_diff_srv_rate  \
0                     0.04                     0.06   
1                     0.00                     0.06   
2                     0.61                     0.04   
3                     1.00                     0.00   
4                     0.31                     0.17   

    dst_host_same_src_port_rate   dst_host_srv_diff_host_rate  \
0                          0.00                          0.00   
1                          0.00                          0.00   
2                          0.61                          0.02   
3                          1.00                          0.28   
4                          0.03                          0.02   

    dst_host_serror_rate    dst_host_srv_serror_rate   dst_host_rerror_rate  \
0                    0.0                         0.0                   1.00   
1                    0.0                         0.0                   1.00   
2                    0.0                         0.0                   0.00   
3                    0.0                         0.0                   0.00   
4                    0.0                         0.0                   0.83   

    dst_host_srv_rerror_rate   classification.  
0                       1.00               Dos  
1                       1.00               Dos  
2                       0.00            normal  
3                       0.00             Probe  
4                       0.71             Probe  

[5 rows x 42 columns]

In [5]:
df_test.columns

Index(['duration', ' protocol_type', ' service', ' flag', ' src_bytes',
       ' dst_bytes', ' land', ' wrong_fragment', ' urgent', ' hot',
       ' num_failed_loginsì', ' logged_in', ' num_compromised', ' root_shell',
       ' su_attempted', ' num_root', ' num_file_creations', ' num_shells',
       ' num_access_files', ' num_outbound_cmds', ' is_host_login',
       ' is_guest_login', ' count', ' srv_count', ' serror_rate',
       ' srv_serror_rate', ' rerror_rate', ' srv_rerror_rate',
       ' same_srv_rate', ' diff_srv_rate', ' srv_diff_host_rate',
       ' dst_host_count', ' dst_host_srv_count', ' dst_host_same_srv_rate',
       ' dst_host_diff_srv_rate', ' dst_host_same_src_port_rate',
       ' dst_host_srv_diff_host_rate', ' dst_host_serror_rate',
       '  dst_host_srv_serror_rate', ' dst_host_rerror_rate',
       ' dst_host_srv_rerror_rate', ' classification.'],
      dtype='object')

In [6]:
df_train.rename(columns = lambda x: x.strip().lower().replace(".", ""), inplace = True)
df_test.rename(columns = lambda x: x.strip().lower().replace(".", ""), inplace = True)

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   duration                     125973 non-null  int64  
 1   protocol_type                125973 non-null  object 
 2   service                      125973 non-null  object 
 3   flag                         125973 non-null  object 
 4   src_bytes                    125973 non-null  int64  
 5   dst_bytes                    125973 non-null  int64  
 6   land                         125973 non-null  int64  
 7   wrong_fragment               125973 non-null  int64  
 8   urgent                       125973 non-null  int64  
 9   hot                          125973 non-null  int64  
 10  num_failed_loginsì           125973 non-null  int64  
 11  logged_in                    125973 non-null  int64  
 12  num_compromised              125973 non-null  int64  
 13 

In [8]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22544 entries, 0 to 22543
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   duration                     22544 non-null  int64  
 1   protocol_type                22544 non-null  object 
 2   service                      22544 non-null  object 
 3   flag                         22544 non-null  object 
 4   src_bytes                    22544 non-null  int64  
 5   dst_bytes                    22544 non-null  int64  
 6   land                         22544 non-null  int64  
 7   wrong_fragment               22544 non-null  int64  
 8   urgent                       22544 non-null  int64  
 9   hot                          22544 non-null  int64  
 10  num_failed_loginsì           22544 non-null  int64  
 11  logged_in                    22544 non-null  int64  
 12  num_compromised              22544 non-null  int64  
 13  root_shell      

In [9]:
df_train.nunique() 

duration                       2981
protocol_type                     3
service                          70
flag                             11
src_bytes                      3341
dst_bytes                      9326
land                              2
wrong_fragment                    3
urgent                            4
hot                              28
num_failed_loginsì                6
logged_in                         2
num_compromised                  88
root_shell                        2
su_attempted                      3
num_root                         82
num_file_creations               35
num_shells                        3
num_access_files                 10
num_outbound_cmds                 1
is_host_login                     2
is_guest_login                    2
count                           512
srv_count                       509
serror_rate                      89
srv_serror_rate                  86
rerror_rate                      82
srv_rerror_rate             

In [10]:
df_test.nunique() 

duration                        624
protocol_type                     3
service                          64
flag                             11
src_bytes                      1149
dst_bytes                      3650
land                              2
wrong_fragment                    3
urgent                            4
hot                              16
num_failed_loginsì                5
logged_in                         2
num_compromised                  23
root_shell                        2
su_attempted                      3
num_root                         20
num_file_creations                9
num_shells                        4
num_access_files                  5
num_outbound_cmds                 1
is_host_login                     2
is_guest_login                    2
count                           495
srv_count                       457
serror_rate                      88
srv_serror_rate                  82
rerror_rate                      90
srv_rerror_rate             

In [11]:
df_train.describe()

duration     src_bytes     dst_bytes           land  \
count  125973.00000  1.259730e+05  1.259730e+05  125973.000000   
mean      287.14465  4.556674e+04  1.977911e+04       0.000198   
std      2604.51531  5.870331e+06  4.021269e+06       0.014086   
min         0.00000  0.000000e+00  0.000000e+00       0.000000   
25%         0.00000  0.000000e+00  0.000000e+00       0.000000   
50%         0.00000  4.400000e+01  0.000000e+00       0.000000   
75%         0.00000  2.760000e+02  5.160000e+02       0.000000   
max     42908.00000  1.379964e+09  1.309937e+09       1.000000   

       wrong_fragment         urgent            hot  num_failed_loginsì  \
count   125973.000000  125973.000000  125973.000000       125973.000000   
mean         0.022687       0.000111       0.204409            0.001222   
std          0.253530       0.014366       2.149968            0.045239   
min          0.000000       0.000000       0.000000            0.000000   
25%          0.000000       0.000000       0.000000            0.000000   
50%          0.000000       0.000000       0.000000            0.000000   
75%          0.000000       0.000000       0.000000            0.000000   
max          3.000000       3.000000      77.000000            5.000000   

           logged_in  num_compromised  ...  dst_host_count  \
count  125973.000000    125973.000000  ...   125973.000000   
mean        0.395736         0.279250  ...      182.148945   
std         0.489010        23.942042  ...       99.206213   
min         0.000000         0.000000  ...        0.000000   
25%         0.000000         0.000000  ...       82.000000   
50%         0.000000         0.000000  ...      255.000000   
75%         1.000000         0.000000  ...      255.000000   
max         1.000000      7479.000000  ...      255.000000   

       dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count       125973.000000           125973.000000           125973.000000   
mean           115.653005                0.521242                0.082951   
std            110.702741                0.448949                0.188922   
min              0.000000                0.000000                0.000000   
25%             10.000000                0.050000                0.000000   
50%             63.000000                0.510000                0.020000   
75%            255.000000                1.000000                0.070000   
max            255.000000                1.000000                1.000000   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                125973.000000                125973.000000   
mean                      0.148379                     0.032542   
std                       0.308997                     0.112564   
min                       0.000000                     0.000000   
25%                       0.000000                     0.000000   
50%                       0.000000                     0.000000   
75%                       0.060000                     0.020000   
max                       1.000000                     1.000000   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count         125973.000000             125973.000000         125973.000000   
mean               0.284452                  0.278485              0.118832   
std                0.444784                  0.445669              0.306557   
min                0.000000                  0.000000              0.000000   
25%                0.000000                  0.000000              0.000000   
50%                0.000000                  0.000000              0.000000   
75%                1.000000                  1.000000              0.000000   
max                1.000000                  1.000000              1.000000   

       dst_host_srv_rerror_rate  
count             125973.000000  
mean                   0.120240  
std                    0.319459  
min                    0.000000  
2

In [12]:
df_test.describe()

duration     src_bytes     dst_bytes          land  wrong_fragment  \
count  22544.000000  2.254400e+04  2.254400e+04  22544.000000    22544.000000   
mean     218.859076  1.039545e+04  2.056019e+03      0.000311        0.008428   
std     1407.176612  4.727864e+05  2.121930e+04      0.017619        0.142599   
min        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
25%        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
50%        0.000000  5.400000e+01  4.600000e+01      0.000000        0.000000   
75%        0.000000  2.870000e+02  6.010000e+02      0.000000        0.000000   
max    57715.000000  6.282565e+07  1.345927e+06      1.000000        3.000000   

             urgent           hot  num_failed_loginsì     logged_in  \
count  22544.000000  22544.000000        22544.000000  22544.000000   
mean       0.000710      0.105394            0.021647      0.442202   
std        0.036473      0.928428            0.150328      0.496659   
min        0.000000      0.000000            0.000000      0.000000   
25%        0.000000      0.000000            0.000000      0.000000   
50%        0.000000      0.000000            0.000000      0.000000   
75%        0.000000      0.000000            0.000000      1.000000   
max        3.000000    101.000000            4.000000      1.000000   

       num_compromised  ...  dst_host_count  dst_host_srv_count  \
count     22544.000000  ...    22544.000000        22544.000000   
mean          0.119899  ...      193.869411          140.750532   
std           7.269597  ...       94.035663          111.783972   
min           0.000000  ...        0.000000            0.000000   
25%           0.000000  ...      121.000000           15.000000   
50%           0.000000  ...      255.000000          168.000000   
75%           0.000000  ...      255.000000          255.000000   
max         796.000000  ...      255.000000          255.000000   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count            22544.000000            22544.000000   
mean                 0.608722                0.090540   
std                  0.435688                0.220717   
min                  0.000000                0.000000   
25%                  0.070000                0.000000   
50%                  0.920000                0.010000   
75%                  1.000000                0.060000   
max                  1.000000                1.000000   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                 22544.000000                 22544.000000   
mean                      0.132261                     0.019638   
std                       0.306268                     0.085394   
min                       0.000000                     0.000000   
25%                       0.000000                     0.000000   
50%                       0.000000                     0.000000   
75%                       0.030000                     0.010000   
max                       1.000000                     1.000000   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count          22544.000000              22544.000000          22544.000000   
mean               0.097814                  0.099426              0.233385   
std                0.273139                  0.281866              0.387229   
min                0.000000                  0.000000              0.000000   
25%                0.000000                  0.000000              0.000000   
50%                0.000000                  0.000000              0.000000   
75%                0.000000                  0.000000              0.360000   
max                1.000000                  1.000000              1.000000   

       dst_host_srv_rerror_rate  
count              22544.000000  
mean                   0.226683  
std                    0.400875  
min                    0.000000  
25%                    0.000000  
50%

In [13]:
df_train.classification.value_counts()

normal    67343
Dos       45927
Probe     11656
R2L         995
U2R          52
Name: classification, dtype: int64

In [14]:
df_test.classification.value_counts()

normal    9711
Dos       7458
R2L       2754
Probe     2421
U2R        200
Name: classification, dtype: int64

In [15]:
# Check duplicated data
df_train.duplicated().sum()

9

In [16]:
# Drop duplicated data
df_train.drop_duplicates(inplace = True)

# Check for any duplicated values
df_train.duplicated().sum().any()

False

In [17]:
# Check duplicated data
df_test.duplicated().sum()

3

In [18]:
# Drop duplicated data
df_test.drop_duplicates(inplace = True)

# Check for any duplicated values
df_test.duplicated().sum().any()

False

In [19]:
# print number of NaN Values
df_train.isnull().sum().sum().any()

False

In [20]:
# print number of NaN Values
df_test.isnull().sum().sum().any()

False

In [21]:
df_train.to_csv('Clean_KDDTrain.csv', index = False)
df_test.to_csv('Clean_KDDTest.csv', index = False)

In [22]:
# independant and dependant variables
X_train = df_train.iloc[:,:-1].values # independent variables
y_train = df_train.iloc[:,-1].values # dependent variable

In [23]:
# independant and dependant variables
X_test = df_test.iloc[:,:-1].values # independent variables
y_test = df_test.iloc[:,-1].values # dependent variable

In [24]:
print(X_train.shape)

(125964, 41)


In [25]:
print(X_test.shape)

(22541, 41)


In [26]:
# y_train[y_train != 'normal'] = 'anomaly'

In [27]:
# Check whether the dataset is equally splitted or not
from collections import Counter
print(y_train) 
print(Counter(y_train))

['normal' 'normal' 'Dos' ... 'normal' 'Dos' 'normal']
Counter({'normal': 67343, 'Dos': 45927, 'Probe': 11647, 'R2L': 995, 'U2R': 52})


In [28]:
#y_test[y_test != 'normal'] = 'anomaly'

In [29]:
print(y_test) 
print(Counter(y_test))

['Dos' 'Dos' 'normal' ... 'Dos' 'normal' 'Probe']
Counter({'normal': 9711, 'Dos': 7458, 'R2L': 2754, 'Probe': 2418, 'U2R': 200})


In [30]:
# # Encoding indepedant variables
# from sklearn.preprocessing import LabelEncoder
# le_y = LabelEncoder() # LabelEncoder for 1-d array

In [31]:
# y_train = le_y.fit_transform(y_train) # does the same what fit() and transform do in one step
# print(y_train)

In [32]:
# y_test = le_y.fit_transform(y_test) # does the same what fit() and transform do in one step
# print(y_test)

In [33]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
X_le = LabelEncoder()
X_train[:,1] = X_le.fit_transform(X_train[:,1])
X_train[:,2] = X_le.fit_transform(X_train[:,2])
X_train[:,3] = X_le.fit_transform(X_train[:,3])

In [34]:
X_test[:,1] = X_le.fit_transform(X_test[:,1])
X_test[:,2] = X_le.fit_transform(X_test[:,2])
X_test[:,3] = X_le.fit_transform(X_test[:,3])

In [35]:
print(X_train[:,1:4])

[[1 20 9]
 [2 44 9]
 [1 49 5]
 ...
 [1 54 9]
 [1 30 5]
 [1 20 9]]


In [36]:
print(X_test[:,1:4])

[[1 45 1]
 [1 45 1]
 [1 19 9]
 ...
 [1 22 9]
 [2 11 9]
 [1 52 1]]


In [37]:
indices = np.r_[0, 4:41]
indices

array([ 0,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

In [38]:
# Scaling for making close variables values from each other
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

# choose [:, indices] for only scaling numerical data
indices = np.r_[0, 4:41]


X_train[:, indices] = sc_X.fit_transform(X_train[:, indices]) # apply fit() on X_train and transform fit on X_train 
X_test[:, indices] = sc_X.transform(X_test[:, indices]) # because we already fit() on x_train we only transform fit on X_test

In [39]:
# Building SVM classifier
from sklearn.svm import SVC
classifier =  SVC(C = 10, kernel = 'rbf', gamma = 'auto')

In [40]:
classifier.fit(X_train,y_train)

SVC(C=10, gamma='auto')

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(y_test, y_pred)*100
print("Accuracy of Support Vector Machine: {}\n".format(accuracy))
print(classification_report(y_test,y_pred, zero_division = 0))

Accuracy of Support Vector Machine: 77.53870724457656

              precision    recall  f1-score   support

         Dos       0.97      0.84      0.90      7458
       Probe       0.84      0.68      0.75      2418
         R2L       0.94      0.03      0.07      2754
         U2R       0.29      0.01      0.02       200
      normal       0.68      0.98      0.80      9711

    accuracy                           0.78     22541
   macro avg       0.74      0.51      0.51     22541
weighted avg       0.82      0.78      0.73     22541



In [43]:
# np.save('X_train', X_train)
# clf_report = classification_report(y_test,y_pred, zero_division = 0)

In [44]:
def stepc(A, Di):
    try:
        c = 1/(1+ np.exp(10*(A*Di-0.5)))
    except Exception as e:
        return 0
    else:
        return c

In [45]:
def stepb(A, Di, r):
    if stepc(A,Di) >= r:
        return 1
    else:
        return 0

In [46]:
def X_d(X, A, Di, rand):
    r = rand.random()
    if (X + stepb(A, Di, r)) >= 1:
        return 1
    else:
        return 0

In [47]:
def cross_over(X_d1, X_d2, X_d3, rand):
    r = rand.random()
    if r < 1/3:
        return X_d1
    elif r >= 1/3 and r < 2/3:
        return X_d2
    else:
        return X_d3

In [48]:
def sigmoid(X):
    try: 
        res = 1/(1+ np.exp(-X))
    except Exception as e:
        print(e)
    else:
        if res >= 0.5:
            return 1
        else:
            return 0

In [49]:
def Fitness(P, NF, a = 0.6, b = 0.4):
    """P is the classification accuracy/detection rate, NF is the length of the selected feature, where a and b are the parameters
    corresponding to the classification accuracy weight and quality of feature selection, a = [0, 1] and b = 1 − a"""
    try: 
        fitness =  a*P + b*(1/NF)
    except ZeroDivisionError as e:
        return a*P
    else:
        return fitness

In [50]:
def objective_function(Selected_Features):
    # read and split the data in X_train, y_train, X_test, y_test
    print(Selected_Features)
    X_train, y_train, X_test, y_test = get_data()
    count = sum(Selected_Features)
    if count == 0:
        return np.NINF, 0
    index = []
    scaling_index = []
    
    for i in range(41):
        if Selected_Features[i] == 1:
            if i not in [1,2,3]:
                scaling_index.append(i)
            index.append(i)
    indices = np.r_[index]
    
    scaling_indices = np.r_[scaling_index]
    print(scaling_indices)
    global sc_X
    sc_X = StandardScaler()
    X_train[:,scaling_indices] = sc_X.fit_transform(X_train[:,scaling_indices])
    X_test[:,scaling_indices] = sc_X.transform(X_test[:,scaling_indices])
    
    X_train = X_train[:, indices]
    X_test = X_test[:, indices]
    
    global classifier
    classifier.fit(X_train,y_train)
    y_pred = classifier.predict(X_test)
    acc_score = accuracy_score(y_test, y_pred)*100 
    fitness = Fitness(acc_score, count, a = 0.6, b = 0.4)
    print(acc_score, fitness)
    return fitness, acc_score

In [51]:
class wolf:
    def __init__(self, fitness, dim, seed, lb, ub):
        self.features = [1 for i in range(dim)]
        self.rand = random.Random(seed)
        self.position = [0.0 for i in range(dim)]
        self.score = accuracy
        for i in range(dim):
            self.position[i] = ((ub - lb) * self.rand.random() + lb)
        self.fitness = fitness(self.score, dim)
        

In [82]:
def GWO(fitness, dim, N, max_iter, lb, ub):
    # initialize the grey wolf population
    population = [ wolf(fitness, dim, i, lb, ub) for i in range(N)] 
    
    # initialize b, A and C
    rand = random.Random()
    b = 2 - 0 * (2/max_iter)
    A1, A2, A3 = b * (2 * rand.random() - 1), b * (
            2 * rand.random() - 1), b * (2 * rand.random() - 1)
    C1, C2, C3 = 2*rand.random(), 2*rand.random(), 2*rand.random()
    
    # Calculate the fitness of each search agent
    population = sorted(population, key = lambda x : x.fitness, reverse=True)
    alpha_wolf, beta_wolf, gamma_wolf = copy.copy(population[:3])
    print(alpha_wolf.fitness, beta_wolf.fitness, gamma_wolf.fitness)
    
    # while iteration : max_iteration
    iteration = 1
    while iteration <= max_iter:
    
        # for each search agent
        for i in range(N):
            X1 = [0.0 for i in range(dim)]
            X2 = [0.0 for i in range(dim)]
            X3 = [0.0 for i in range(dim)]
            Xnew = [0.0 for i in range(dim)]
            X_dnew = [0 for i in range(dim)]
            for j in range(dim):
                # Calculate W1, W2, W3
                D_alpha = abs(C1 * alpha_wolf.position[j] - population[i].position[j])
                D_beta = abs(C2 *  beta_wolf.position[j] - population[i].position[j])
                D_gamma = abs(C3 * gamma_wolf.position[j] - population[i].position[j])
                
                # grey wolf optmization
                # Update the position of the current search agent
                X1[j] = alpha_wolf.position[j] - A1 * D_alpha
                X2[j] = beta_wolf.position[j] - A2 * D_beta
                X3[j] = gamma_wolf.position[j] - A3 * D_gamma
                Xnew[j] = (X1[j] + X2[j] + X3[j]) /3.0
    
                X_dnew[j] = sigmoid(Xnew[j])
                                

            # Calculate the fitness of all search agent
            NF = sum(X_dnew)
            print(NF)
            fnew, score = 0, 0
            if NF == dim:
                score = accuracy
                fnew = fitness(score, NF, 0.6, 0.4)
            else:
                fnew , score = objective_function(X_dnew)  
            if fnew > population[i].fitness:
                population[i].position = copy.copy(Xnew)
                population[i].fitness = fnew
                population[i].features = copy.copy(X_dnew)
                population[i].score = score
        
        # Update b, A, and C
        b = 2 - iteration * (2/max_iter)
        A1, A2, A3 = b * (2 * rand.random() - 1), b * (
            2 * rand.random() - 1), b * (2 * rand.random() - 1)
        C1, C2, C3 = 2*rand.random(), 2*rand.random(), 2*rand.random()
        
        # Update alpha_wolf, beta_wolf, gamma_wolf
        population = sorted(population, key = lambda x: x.fitness, reverse=True)
        alpha_wolf, beta_wolf, gamma_wolf = copy.copy(population[:3])
        print(alpha_wolf.fitness, beta_wolf.fitness, gamma_wolf.fitness)
        print("Iteration = {} best fitness = {} score = {} NF = {} ".format(str(iteration), alpha_wolf.fitness, alpha_wolf.score, sum(alpha_wolf.features)))
        
        # iteration = iteration + 1
        iteration+=1
    print(alpha_wolf.features)    
    return alpha_wolf

In [83]:
def bGWO(fitness, dim, N, max_iter, lb, ub):
    # initialize the grey wolf population
    population = [ wolf(fitness, dim, i, lb, ub) for i in range(N)] 
    
    # initialize b, A and C
    rand = random.Random()
    b = 2 - 0 * (2/max_iter)
    A1, A2, A3 = b * (2 * rand.random() - 1), b * (
            2 * rand.random() - 1), b * (2 * rand.random() - 1)
    C1, C2, C3 = 2*rand.random(), 2*rand.random(), 2*rand.random()
    
    # Calculate the fitness of each search agent
    population = sorted(population, key = lambda x : x.fitness, reverse=True)
    alpha_wolf, beta_wolf, gamma_wolf = copy.copy(population[:3])
    print(alpha_wolf.fitness, beta_wolf.fitness, gamma_wolf.fitness)
    
    # while iteration < max_iteration
    iteration = 1
    while iteration <= max_iter:

        # for each search agent
        for i in range(N):
            X1 = [0.0 for i in range(dim)]
            X2 = [0.0 for i in range(dim)]
            X3 = [0.0 for i in range(dim)]
            Xnew = [0.0 for i in range(dim)]

            X_d1 = [0 for i in range(dim)]
            X_d2 = [0 for i in range(dim)]
            X_d3 = [0 for i in range(dim)]
            X_dnew = [0 for i in range(dim)]
            for j in range(dim):
                # Calculate W1, W2, W3
                D_alpha = abs(C1 * alpha_wolf.position[j] - population[i].position[j])
                D_beta = abs(C2 *  beta_wolf.position[j] - population[i].position[j])
                D_gamma = abs(C3 * gamma_wolf.position[j] - population[i].position[j])
                
                # grey wolf optmization
                # Update the position of the current search agent
                X1[j] = alpha_wolf.position[j] - A1 * D_alpha
                X2[j] = beta_wolf.position[j] - A2 * D_beta
                X3[j] = gamma_wolf.position[j] - A3 * D_gamma
                Xnew[j] = (X1[j] + X2[j] + X3[j]) /3.0
                if Xnew[j] < lb:
                    Xnew[j] = lb
                elif Xnew[j] > ub:
                    Xnew[j] = ub
                                
                # binary grey wolf optmization 1, 0
                X_d1[j] = X_d(alpha_wolf.position[j], A1, D_alpha, rand)
                X_d2[j] = X_d(alpha_wolf.position[j], A2, D_beta, rand)
                X_d3[j] = X_d(alpha_wolf.position[j], A3, D_gamma, rand)
                X_dnew[j] = cross_over(X_d1[j], X_d2[j], X_d3[j], rand) # 1 or 0
            
            # Calculate the fitness of all search agent
            NF = sum(X_dnew)
            print(NF)
            fnew, score = 0, 0
            if NF == dim:
                score = accuracy
                fnew = fitness(score, NF, 0.6, 0.4)
            else:
                fnew , score = objective_function(X_dnew)  
            if fnew > population[i].fitness:
                population[i].position =  copy.copy(Xnew)
                population[i].fitness = fnew
                population[i].features = copy.copy(X_dnew)
                population[i].score = score
        
        # Update b, A, and C
        b = 2 - iteration * (2/max_iter)
        A1, A2, A3 = b * (2 * rand.random() - 1), b * (
            2 * rand.random() - 1), b * (2 * rand.random() - 1)
        C1, C2, C3 = 2*rand.random(), 2*rand.random(), 2*rand.random()
        
        # Update alpha_wolf, beta_wolf, gamma_wolf
        population = sorted(population, key = lambda x: x.fitness, reverse=True)
        alpha_wolf, beta_wolf, gamma_wolf = copy.copy(population[:3])
        print(alpha_wolf.fitness, beta_wolf.fitness, gamma_wolf.fitness)
        print("Iteration = {} best fitness = {} score = {} NF = {} ".format(str(iteration), alpha_wolf.fitness, alpha_wolf.score, sum(alpha_wolf.features)))
        
        # iteration = iteration + 1
        iteration+=1
    print(alpha_wolf.features)    
    return alpha_wolf

In [54]:
def perf_measure(y_actual, y_pred, value):
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    for i in range(len(y_pred)): 
        if y_actual[i]==y_pred[i]==value:
            TP += 1
        if y_pred[i]==value and y_actual[i]!=y_pred[i]:
            FP += 1
        if y_actual[i]==y_pred[i]!=value:
            TN += 1
        if y_pred[i]!= value and y_actual[i]!=y_pred[i]:
            FN += 1

    return(TP, FP, TN, FN)

In [55]:
def AAP(AC, run):
    """AC is the accuracy rate"""
    return sum(AC)/run

In [56]:
def ANF(NF, run):
    """NF is the number of features"""
    return sum(NF)/run

In [57]:
def AC(TP, FP, TN, FN):
    return (TP+TN)/(TP+FP+TN+FN)

In [58]:
# Can be used for MBGWO for further work
def DR(TP,FN):
    return TP/(TP+FN)

In [59]:
def scaling_x(X, key):
    # Scaling for making close variables values from each other
    from sklearn.preprocessing import StandardScaler
    sc_X = StandardScaler()
    if key == 'train':
        X = sc_X.fit_transform(X)
    elif key == 'test':
        X = sc_X.transform(X)
    return X

In [60]:
def model_building(X_train, X_test, y_train, FS):
    index = []
    scaling_index = []
    for i in range(41):
        if FS[i] == 1:
            if i not in [1,2,3]:
                scaling_index.append(i)
            index.append(i)
    indices = np.r_[index]
    scaling_indices = np.r_[scaling_index]
    global sc_X
    sc_X = StandardScaler()
    X_train[:,scaling_indices] = sc_X.fit_transform(X_train[:,scaling_indices])
    X_test[:,scaling_indices] = sc_X.transform(X_test[:,scaling_indices])
    
    Xnew_train = X_train[:, indices]
    Xnew_test = X_test[:, indices]
    global classifier
    classifier.fit(Xnew_train,y_train)
    return classifier, Xnew_test

In [61]:
def generate(selected_features):
    count = sum(selected_features)
    if count == 0:
        return np.NINF, 0
    print(selected_features)
    X_train, y_train, X_test, y_test = get_data()
    global classifier
    classifier, X_test = model_building(X_train, X_test, y_train, selected_features)
    y_pred = classifier.predict(X_test)
    clf_report = classification_report(y_test,y_pred, zero_division = 0)
    acc_score = accuracy_score(y_test, y_pred)*100
    print("Accuracy of Support Vector Machine: {}\n".format(acc_score))
    print(classification_report(y_test,y_pred, zero_division = 0))
    fitness = Fitness(acc_score, count, a = 0.6, b = 0.4)
    print(fitness)

    return classifier, clf_report
    

In [62]:
def get_data():
    df_train = pd.read_csv('Clean_KDDTrain.csv')
    df_test = pd.read_csv('Clean_KDDTest.csv')
    # tain data
    X_train = df_train.iloc[:,:-1].values # independent variables
    y_train = df_train.iloc[:,-1].values # dependent variable
    
    # test data
    X_test = df_test.iloc[:,:-1].values # independent variables
    y_test = df_test.iloc[:,-1].values # dependent variable
    
    # Encoding categorical data
    from sklearn.preprocessing import LabelEncoder
    X_le = LabelEncoder()
    X_train[:,1] = X_le.fit_transform(X_train[:,1])
    X_train[:,2] = X_le.fit_transform(X_train[:,2])
    X_train[:,3] = X_le.fit_transform(X_train[:,3])

    X_test[:,1] = X_le.fit_transform(X_test[:,1])
    X_test[:,2] = X_le.fit_transform(X_test[:,2])
    X_test[:,3] = X_le.fit_transform(X_test[:,3])
    
    return X_train, y_train, X_test, y_test

In [63]:
def get_input():
    try: 
        run  =  int(E1.get())
        N = int(E2.get())
        max_iter = int(E3.get())
        optimizer = str(E4.get())
    except Exception as e:
        print(e)
    else:
        return run, N, max_iter, optimizer

In [64]:
def test_result():
    global pred_label, top, classifier, sc_X, cat_features
    input_list = []
    cnt = 0
    scaling_index = []
    try:
        for t in T1:
            if cnt not in cat_features:
                scaling_index.append(cnt)
            input_list.append(np.float(t.get()))
            cnt += 1
    except Exception as e:
        print(e)
    else:
        
        scaling_indices = np.r_[scaling_index]
        X = np.array(input_list).reshape(1,-1)
       
        print(scaling_indices)
        print(input_list)
        print(X)
        X[:,scaling_indices] = sc_X.transform(X[:,scaling_indices])
        print(X)
        y = classifier.predict(X)
        pred_label.pack_forget()
        pred_label = Label(top, text = f"Predicted Attack: {y}")
        pred_label.pack()

In [65]:
# FS = [1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,1,1,0,0,1,1,0,1,1,1,0,1,1,1]
def create_testframe(FS): 
    global F1, T1, top, pred_label, cat_features
    if top != None:
        top.destroy()
    top = Tk()
    top.title("Test The IDS")
    top.minsize(1024,512)
    L = Label(top, text= "Test The IDS model using GWO-SVM")
    L.pack(pady = 10)
    frame3 = LabelFrame(top, text = "Test The IDS ", padx = 50,pady = 10)
    frame3.pack(pady = 10)
    cat_features = []
    F1, T1 = [],[]
    index = []
    for i in range(41):
        if FS[i] == 1:
            index.append(i)
    indices = np.r_[index]
    df = df_train.iloc[[0],indices]
    columns = df.columns
    for i in range(0,sum(FS)):
        if columns[i] in ['protocol_type','service','flag']:
            cat_features.append(i)
        F1.append(Label(frame3, text = f"{columns[i]}: "))
        F1[i].grid_forget()
        T1.append(Entry(frame3))
        T1[i].grid_forget()
        if i < sum(FS)/3 :
            F1[i].grid(row = i, column = 0)
            T1[i].grid(row = i, column = 1, padx =5, pady=5)
        elif i < 2*(sum(FS)/3):
            F1[i].grid(row = int(i%(sum(FS)/3)), column = 3)
            T1[i].grid(row = int(i%(sum(FS)/3)), column = 4, padx =5, pady=5)
        else:
            F1[i].grid(row = int(i%(2*(sum(FS)/3))), column = 5)
            T1[i].grid(row = int(i%(2*(sum(FS)/3))), column = 6, padx =5, pady=5)
         
    btn2 = Button(top , text = 'Submit', command = test_result, padx = 20, pady =10, bg='brown', fg='white')
    btn2.pack_forget()
    btn2.pack(padx = 30, pady= 20)
    pred_label = Label(top, text = "Predicted Attack")
    
    top.mainloop()


In [66]:
def clf_table(clf_report):
    global my_tree
    if my_tree != None:
        my_tree.pack_forget()
    my_tree = ttk.Treeview(frame2, show = 'headings')
    my_tree['columns'] = ('name', 'precision', 'recall', 'f1-score', 'support')
    my_tree.pack()

    my_tree.column('name', width = 80, minwidth = 60)
    my_tree.column('precision', width = 80, minwidth = 60)
    my_tree.column('recall', width = 80, minwidth = 60)
    my_tree.column('f1-score', width = 80, minwidth = 60)
    my_tree.column('support', width = 80, minwidth = 60)

    my_tree.heading('name', text ='Name')
    my_tree.heading('precision', text ='Precision')
    my_tree.heading('recall', text ='Recall')
    my_tree.heading('f1-score', text ='F1-score')
    my_tree.heading('support', text ='Support')   
    
    my_list = clf_report.split()
    for i in range(4,29,5):
        my_tree.insert('','end', values = my_list[i:i+5])
    my_tree.insert('','end', values = ' ')
    my_tree.insert('','end', values = (my_list[29], ' ', ' ',my_list[30],my_list[31]))
    for i in range(32,44,6):
        my_list[i+1] = " ".join(my_list[i:i+2])
        my_tree.insert('','end', values = my_list[i+1:i+6])

In [67]:
# Function of what happens when you press btn1
def btn1Action():
    global res, top
    # get data from txtfiled
    dim, lb, ub = 41, 0, 1
    fitness = Fitness
    run, N, max_iter, optimizer = get_input()
    fs_list, fs_count, scores = [], [], []
    best_alpha_wolf =  wolf(fitness, dim, N, lb, ub)
    print(best_alpha_wolf.fitness, best_alpha_wolf.score, sum(best_alpha_wolf.features))
    best_score, best_features = accuracy, [1 for i in range(dim)]
    for i in range(run):
        if optimizer == "bGWO":
            alpha_w = bGWO(fitness, dim, N, max_iter, lb, ub)
        elif optimizer == "GWO":
            alpha_w = GWO(fitness, dim, N, max_iter, lb, ub)
        else:
            return
        fs_list.append(alpha_w.features)
        fs_count.append(sum(alpha_w.features))
        scores.append(alpha_w.score)
        if alpha_w.score > best_score:
            best_score = alpha_w.score
            best_features = alpha_w.features
        if alpha_w.fitness >= best_alpha_wolf.fitness: 
            best_alpha_wolf = copy.copy(alpha_w)
        print(best_alpha_wolf.fitness, alpha_w.fitness)
       
    if res != None:
        for r in res:
            r.pack_forget()
    res = []
    res.append(Label(frame2, text = f"Best Accuarcy: {best_score}")) 
    res.append(Label(frame2, text = f"Selected Features Count of Best Accuarcy: {sum(best_features)}"))
    res.append(Label(frame2, text = f"Best Fitness: {best_alpha_wolf.fitness}")) 
    res.append(Label(frame2, text = f"Accuarcy of Best Fitness: {best_alpha_wolf.score}")) 
    res.append(Label(frame2, text = f"Selected Feature Count: {sum(best_alpha_wolf.features)}"))
    res.append(Label(frame2, text = f"{best_alpha_wolf.features}"))
    res.append(Label(frame2, text = f"The average accuracy performance: {AAP(scores,run)}"))
    res.append(Label(frame2, text = f"The average of the subset selected features: {int(ANF(fs_count, run))}"))
    for r in res:
        r.pack(pady = 1)
    
    global classifier
    classifier, clf_report= generate(best_alpha_wolf.features)
    clf_table(clf_report)
    create_testframe(best_alpha_wolf.features)
    top = None

In [84]:
root = Tk()
root.title('Gray Wolf Optimizer')
root.minsize(755,555)
# root.iconbitmap("path_to_icon")

try:
    frame1 = LabelFrame(root, text = "Initialization ", padx= 50, pady=20)
    frame1.pack(pady = 10)

    L0 = Label(frame1, text = "Intrusion Detection System using GWO")
    L0.pack()

    nested_frame = LabelFrame(frame1, text = "Parameters ", padx= 50 , pady = 10)
    nested_frame.pack()
    ###################################
    L1 = Label(nested_frame, text = "Enter number of runs: ", anchor = W)
    L1.grid(row = 0, column = 0 )

    E1 = Entry(nested_frame)
    E1.grid(row = 0, column = 1)
    E1.insert(0, "5")

    L2 = Label(nested_frame, text = "Enter number of population: ", anchor = W)
    L2.grid(row = 1, column = 0, pady = 5)

    E2 = Entry(nested_frame)
    E2.grid(row = 1, column = 1, pady = 5)
    E2.insert(0, "12")

    L3 = Label(nested_frame, text = "Enter number of iterations: ", anchor = W)
    L3.grid(row = 2, column = 0)

    E3 = Entry(nested_frame)
    E3.grid(row = 2, column = 1)
    E3.insert(0, "20")
    
    L4 = Label(nested_frame, text = "Type the optimizer function: ", anchor = W)
    L4.grid(row = 3, column = 0)

    E4 = Entry(nested_frame)
    E4.grid(row = 3, column = 1)
    E4.insert(0, "Type GWO or bGWO")
    ###################################
    btn1 = Button(frame1 , text = 'Generate', command = btn1Action, padx = 10, pady = 10, bg='brown', fg='white')
    btn1.pack(pady = 10)
    ###################################################################
    frame2 = LabelFrame(root, text = "Results ", padx = 50,pady = 10)
    frame2.pack(pady = 10)
    L3 = Label(frame2, text = "HERE IS THE RESULTS")
except Exception as e:
    print(e)
##################################################################
top = None
pred_label = None
my_tree = None
res = None
F1, T1 = [],[]
cat_features = []

# Run The GUI
root.mainloop()

46.53298044430691 77.53870724457656 41
46.53298044430691 46.53298044430691 46.53298044430691
33
[1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  4  5  8  9 11 12 13 14 15 16 17 19 20 23 24 25 26 27 30 31 32 33 34
 35 36 37 38 39 40]
74.72161838427755 44.84509224268774
36
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1]
[ 0  4  5  7  8  9 10 11 12 13 14 15 16 19 20 21 23 24 25 26 27 28 29 30
 31 32 33 34 35 37 38 39 40]
77.21041657424249 46.3373610556566
38
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]
[ 0  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 39 40]
77.81376158999157 46.69878326978442
31
[1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1

[ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 37 38 39 40]
77.44998003637815 46.479988021826884
41
39
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 22 23 24 25 26 27
 28 30 31 32 33 34 35 36 37 38 39 40]
75.46249057273413 45.28775075389689
40
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40]
77.56532540703607 46.549195244221636
40
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 28 29 30 31 32 33 34 35 36 37 38 39 40]
77.72503438179318 46.6450206290759
40
[1, 1, 1, 1, 1,

77.57419812785591 46.554518876713544
37
[1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  4  5  7  8  9 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28
 30 31 32 33 34 35 36 37 38 39 40]
76.41187170045694 45.85793383108497
47.17553287283112 46.72036229477336 46.554518876713544
Iteration = 4 best fitness = 47.17553287283112 score = 78.60787010336719 NF = 37 
40
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40]
77.56088904662614 46.54653342797568
39
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0]
[ 0  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 36 37 38 39]
76.39856261922718 45.849393981792716
41


## Other Feature Selection Methods
**You can try them by your self and check, it is bonus for you**

In [69]:
# Feature Selection
from sklearn.feature_selection import SelectPercentile, GenericUnivariateSelect, SelectKBest, SelectFromModel
from sklearn.feature_selection import chi2, f_classif

fsp = SelectPercentile(score_func = chi2, percentile = 25)
fsgu = GenericUnivariateSelect(score_func = chi2, mode = 'k_best', param = 10)
fskb = SelectKBest(score_func = chi2, k = 10)

In [70]:
# independant and dependant variables
X = df_train.iloc[:,:-1].values # independent variables
y = df_train.iloc[:,-1].values # dependent variable
X[:,1] = X_le.fit_transform(X[:,1])
X[:,2] = X_le.fit_transform(X[:,2])
X[:,3] = X_le.fit_transform(X[:,3])

In [71]:
X_p  = fsp.fit_transform(X, y)
print('Selected Feature are: {}'.format(fsp.get_support()))

Selected Feature are: [ True False  True  True  True  True False False False  True False False
 False False False False False False False False False False  True  True
 False False False False False False False  True  True False False False
 False False False False False]


In [72]:
X_gu = fsgu.fit_transform(X, y)
print('Selected Feature are: {}'.format(fsgu.get_support()))

Selected Feature are: [ True False  True  True  True  True False False False  True False False
 False False False False False False False False False False  True  True
 False False False False False False False  True  True False False False
 False False False False False]


In [73]:
print(fsgu.get_support() == fsp.get_support())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]


In [74]:
X_kb = fskb.fit_transform(X, y)
print('Selected Feature are: {}'.format(fskb.get_support()))

Selected Feature are: [ True False  True  True  True  True False False False  True False False
 False False False False False False False False False False  True  True
 False False False False False False False  True  True False False False
 False False False False False]


In [75]:
print(fsgu.get_support() == fskb.get_support())

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]


In [76]:
# fs_from_model = SelectFromModel(estimator = classifier, max_features = 15 )
# X_fm=fs_from_model.fit_transform(X,y)

In [77]:
# (X.shape, X_fm.shape)