In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline 

In [2]:
df_train = pd.read_csv('KDDTrain+aggregate.csv')
df_train.head()

duration  protocol_type   service  flag   src_bytes   dst_bytes   land  \
0         0            tcp  ftp_data    SF         491           0      0   
1         0            udp     other    SF         146           0      0   
2         0            tcp   private    S0           0           0      0   
3         0            tcp      http    SF         232        8153      0   
4         0            tcp      http    SF         199         420      0   

    wrong_fragment   urgent   hot  ...   dst_host_srv_count  \
0                0        0     0  ...                   25   
1                0        0     0  ...                    1   
2                0        0     0  ...                   26   
3                0        0     0  ...                  255   
4                0        0     0  ...                  255   

    dst_host_same_srv_rate   dst_host_diff_srv_rate  \
0                     0.17                     0.03   
1                     0.00                     0.60   
2                     0.10                     0.05   
3                     1.00                     0.00   
4                     1.00                     0.00   

    dst_host_same_src_port_rate   dst_host_srv_diff_host_rate  \
0                          0.17                          0.00   
1                          0.88                          0.00   
2                          0.00                          0.00   
3                          0.03                          0.04   
4                          0.00                          0.00   

    dst_host_serror_rate    dst_host_srv_serror_rate   dst_host_rerror_rate  \
0                   0.00                        0.00                   0.05   
1                   0.00                        0.00                   0.00   
2                   1.00                        1.00                   0.00   
3                   0.03                        0.01                   0.00   
4                   0.00                        0.00                   0.00   

    dst_host_srv_rerror_rate   classification.  
0                       0.00            normal  
1                       0.00            normal  
2                       0.00               Dos  
3                       0.01            normal  
4                       0.00            normal  

[5 rows x 42 columns]

In [3]:
df_train.columns

Index(['duration', ' protocol_type', ' service', ' flag', ' src_bytes',
       ' dst_bytes', ' land', ' wrong_fragment', ' urgent', ' hot',
       ' num_failed_loginsì', ' logged_in', ' num_compromised', ' root_shell',
       ' su_attempted', ' num_root', ' num_file_creations', ' num_shells',
       ' num_access_files', ' num_outbound_cmds', ' is_host_login',
       ' is_guest_login', ' count', ' srv_count', ' serror_rate',
       ' srv_serror_rate', ' rerror_rate', ' srv_rerror_rate',
       ' same_srv_rate', ' diff_srv_rate', ' srv_diff_host_rate',
       ' dst_host_count', ' dst_host_srv_count', ' dst_host_same_srv_rate',
       ' dst_host_diff_srv_rate', ' dst_host_same_src_port_rate',
       ' dst_host_srv_diff_host_rate', ' dst_host_serror_rate',
       '  dst_host_srv_serror_rate', ' dst_host_rerror_rate',
       ' dst_host_srv_rerror_rate', ' classification.'],
      dtype='object')

In [4]:
df_test = pd.read_csv('KDDTest+aggregate.csv')
df_test.head()

duration  protocol_type   service  flag   src_bytes   dst_bytes   land  \
0         0            tcp   private   REJ           0           0      0   
1         0            tcp   private   REJ           0           0      0   
2         2            tcp  ftp_data    SF       12983           0      0   
3         0           icmp     eco_i    SF          20           0      0   
4         1            tcp    telnet  RSTO           0          15      0   

    wrong_fragment   urgent   hot  ...   dst_host_srv_count  \
0                0        0     0  ...                   10   
1                0        0     0  ...                    1   
2                0        0     0  ...                   86   
3                0        0     0  ...                   57   
4                0        0     0  ...                   86   

    dst_host_same_srv_rate   dst_host_diff_srv_rate  \
0                     0.04                     0.06   
1                     0.00                     0.06   
2                     0.61                     0.04   
3                     1.00                     0.00   
4                     0.31                     0.17   

    dst_host_same_src_port_rate   dst_host_srv_diff_host_rate  \
0                          0.00                          0.00   
1                          0.00                          0.00   
2                          0.61                          0.02   
3                          1.00                          0.28   
4                          0.03                          0.02   

    dst_host_serror_rate    dst_host_srv_serror_rate   dst_host_rerror_rate  \
0                    0.0                         0.0                   1.00   
1                    0.0                         0.0                   1.00   
2                    0.0                         0.0                   0.00   
3                    0.0                         0.0                   0.00   
4                    0.0                         0.0                   0.83   

    dst_host_srv_rerror_rate   classification.  
0                       1.00               Dos  
1                       1.00               Dos  
2                       0.00            normal  
3                       0.00             Probe  
4                       0.71             Probe  

[5 rows x 42 columns]

In [5]:
df_test.columns

Index(['duration', ' protocol_type', ' service', ' flag', ' src_bytes',
       ' dst_bytes', ' land', ' wrong_fragment', ' urgent', ' hot',
       ' num_failed_loginsì', ' logged_in', ' num_compromised', ' root_shell',
       ' su_attempted', ' num_root', ' num_file_creations', ' num_shells',
       ' num_access_files', ' num_outbound_cmds', ' is_host_login',
       ' is_guest_login', ' count', ' srv_count', ' serror_rate',
       ' srv_serror_rate', ' rerror_rate', ' srv_rerror_rate',
       ' same_srv_rate', ' diff_srv_rate', ' srv_diff_host_rate',
       ' dst_host_count', ' dst_host_srv_count', ' dst_host_same_srv_rate',
       ' dst_host_diff_srv_rate', ' dst_host_same_src_port_rate',
       ' dst_host_srv_diff_host_rate', ' dst_host_serror_rate',
       '  dst_host_srv_serror_rate', ' dst_host_rerror_rate',
       ' dst_host_srv_rerror_rate', ' classification.'],
      dtype='object')

In [6]:
df_train.rename(columns = lambda x: x.strip().lower().replace(".", ""), inplace = True)
df_test.rename(columns = lambda x: x.strip().lower().replace(".", ""), inplace = True)

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   duration                     125973 non-null  int64  
 1   protocol_type                125973 non-null  object 
 2   service                      125973 non-null  object 
 3   flag                         125973 non-null  object 
 4   src_bytes                    125973 non-null  int64  
 5   dst_bytes                    125973 non-null  int64  
 6   land                         125973 non-null  int64  
 7   wrong_fragment               125973 non-null  int64  
 8   urgent                       125973 non-null  int64  
 9   hot                          125973 non-null  int64  
 10  num_failed_loginsì           125973 non-null  int64  
 11  logged_in                    125973 non-null  int64  
 12  num_compromised              125973 non-null  int64  
 13 

In [8]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22544 entries, 0 to 22543
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   duration                     22544 non-null  int64  
 1   protocol_type                22544 non-null  object 
 2   service                      22544 non-null  object 
 3   flag                         22544 non-null  object 
 4   src_bytes                    22544 non-null  int64  
 5   dst_bytes                    22544 non-null  int64  
 6   land                         22544 non-null  int64  
 7   wrong_fragment               22544 non-null  int64  
 8   urgent                       22544 non-null  int64  
 9   hot                          22544 non-null  int64  
 10  num_failed_loginsì           22544 non-null  int64  
 11  logged_in                    22544 non-null  int64  
 12  num_compromised              22544 non-null  int64  
 13  root_shell      

In [9]:
df_train.nunique() 

duration                       2981
protocol_type                     3
service                          70
flag                             11
src_bytes                      3341
dst_bytes                      9326
land                              2
wrong_fragment                    3
urgent                            4
hot                              28
num_failed_loginsì                6
logged_in                         2
num_compromised                  88
root_shell                        2
su_attempted                      3
num_root                         82
num_file_creations               35
num_shells                        3
num_access_files                 10
num_outbound_cmds                 1
is_host_login                     2
is_guest_login                    2
count                           512
srv_count                       509
serror_rate                      89
srv_serror_rate                  86
rerror_rate                      82
srv_rerror_rate             

In [10]:
df_test.nunique() 

duration                        624
protocol_type                     3
service                          64
flag                             11
src_bytes                      1149
dst_bytes                      3650
land                              2
wrong_fragment                    3
urgent                            4
hot                              16
num_failed_loginsì                5
logged_in                         2
num_compromised                  23
root_shell                        2
su_attempted                      3
num_root                         20
num_file_creations                9
num_shells                        4
num_access_files                  5
num_outbound_cmds                 1
is_host_login                     2
is_guest_login                    2
count                           495
srv_count                       457
serror_rate                      88
srv_serror_rate                  82
rerror_rate                      90
srv_rerror_rate             

In [11]:
df_train.describe()

duration     src_bytes     dst_bytes           land  \
count  125973.00000  1.259730e+05  1.259730e+05  125973.000000   
mean      287.14465  4.556674e+04  1.977911e+04       0.000198   
std      2604.51531  5.870331e+06  4.021269e+06       0.014086   
min         0.00000  0.000000e+00  0.000000e+00       0.000000   
25%         0.00000  0.000000e+00  0.000000e+00       0.000000   
50%         0.00000  4.400000e+01  0.000000e+00       0.000000   
75%         0.00000  2.760000e+02  5.160000e+02       0.000000   
max     42908.00000  1.379964e+09  1.309937e+09       1.000000   

       wrong_fragment         urgent            hot  num_failed_loginsì  \
count   125973.000000  125973.000000  125973.000000       125973.000000   
mean         0.022687       0.000111       0.204409            0.001222   
std          0.253530       0.014366       2.149968            0.045239   
min          0.000000       0.000000       0.000000            0.000000   
25%          0.000000       0.000000       0.000000            0.000000   
50%          0.000000       0.000000       0.000000            0.000000   
75%          0.000000       0.000000       0.000000            0.000000   
max          3.000000       3.000000      77.000000            5.000000   

           logged_in  num_compromised  ...  dst_host_count  \
count  125973.000000    125973.000000  ...   125973.000000   
mean        0.395736         0.279250  ...      182.148945   
std         0.489010        23.942042  ...       99.206213   
min         0.000000         0.000000  ...        0.000000   
25%         0.000000         0.000000  ...       82.000000   
50%         0.000000         0.000000  ...      255.000000   
75%         1.000000         0.000000  ...      255.000000   
max         1.000000      7479.000000  ...      255.000000   

       dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count       125973.000000           125973.000000           125973.000000   
mean           115.653005                0.521242                0.082951   
std            110.702741                0.448949                0.188922   
min              0.000000                0.000000                0.000000   
25%             10.000000                0.050000                0.000000   
50%             63.000000                0.510000                0.020000   
75%            255.000000                1.000000                0.070000   
max            255.000000                1.000000                1.000000   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                125973.000000                125973.000000   
mean                      0.148379                     0.032542   
std                       0.308997                     0.112564   
min                       0.000000                     0.000000   
25%                       0.000000                     0.000000   
50%                       0.000000                     0.000000   
75%                       0.060000                     0.020000   
max                       1.000000                     1.000000   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count         125973.000000             125973.000000         125973.000000   
mean               0.284452                  0.278485              0.118832   
std                0.444784                  0.445669              0.306557   
min                0.000000                  0.000000              0.000000   
25%                0.000000                  0.000000              0.000000   
50%                0.000000                  0.000000              0.000000   
75%                1.000000                  1.000000              0.000000   
max                1.000000                  1.000000              1.000000   

       dst_host_srv_rerror_rate  
count             125973.000000  
mean                   0.120240  
std                    0.319459  
min                    0.000000  
2

In [12]:
df_test.describe()

duration     src_bytes     dst_bytes          land  wrong_fragment  \
count  22544.000000  2.254400e+04  2.254400e+04  22544.000000    22544.000000   
mean     218.859076  1.039545e+04  2.056019e+03      0.000311        0.008428   
std     1407.176612  4.727864e+05  2.121930e+04      0.017619        0.142599   
min        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
25%        0.000000  0.000000e+00  0.000000e+00      0.000000        0.000000   
50%        0.000000  5.400000e+01  4.600000e+01      0.000000        0.000000   
75%        0.000000  2.870000e+02  6.010000e+02      0.000000        0.000000   
max    57715.000000  6.282565e+07  1.345927e+06      1.000000        3.000000   

             urgent           hot  num_failed_loginsì     logged_in  \
count  22544.000000  22544.000000        22544.000000  22544.000000   
mean       0.000710      0.105394            0.021647      0.442202   
std        0.036473      0.928428            0.150328      0.496659   
min        0.000000      0.000000            0.000000      0.000000   
25%        0.000000      0.000000            0.000000      0.000000   
50%        0.000000      0.000000            0.000000      0.000000   
75%        0.000000      0.000000            0.000000      1.000000   
max        3.000000    101.000000            4.000000      1.000000   

       num_compromised  ...  dst_host_count  dst_host_srv_count  \
count     22544.000000  ...    22544.000000        22544.000000   
mean          0.119899  ...      193.869411          140.750532   
std           7.269597  ...       94.035663          111.783972   
min           0.000000  ...        0.000000            0.000000   
25%           0.000000  ...      121.000000           15.000000   
50%           0.000000  ...      255.000000          168.000000   
75%           0.000000  ...      255.000000          255.000000   
max         796.000000  ...      255.000000          255.000000   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
count            22544.000000            22544.000000   
mean                 0.608722                0.090540   
std                  0.435688                0.220717   
min                  0.000000                0.000000   
25%                  0.070000                0.000000   
50%                  0.920000                0.010000   
75%                  1.000000                0.060000   
max                  1.000000                1.000000   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
count                 22544.000000                 22544.000000   
mean                      0.132261                     0.019638   
std                       0.306268                     0.085394   
min                       0.000000                     0.000000   
25%                       0.000000                     0.000000   
50%                       0.000000                     0.000000   
75%                       0.030000                     0.010000   
max                       1.000000                     1.000000   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
count          22544.000000              22544.000000          22544.000000   
mean               0.097814                  0.099426              0.233385   
std                0.273139                  0.281866              0.387229   
min                0.000000                  0.000000              0.000000   
25%                0.000000                  0.000000              0.000000   
50%                0.000000                  0.000000              0.000000   
75%                0.000000                  0.000000              0.360000   
max                1.000000                  1.000000              1.000000   

       dst_host_srv_rerror_rate  
count              22544.000000  
mean                   0.226683  
std                    0.400875  
min                    0.000000  
25%                    0.000000  
50%

In [13]:
df_train.classification.value_counts()

normal    67343
Dos       45927
Probe     11656
R2L         995
U2R          52
Name: classification, dtype: int64

In [14]:
df_test.classification.value_counts()

normal    9711
Dos       7458
R2L       2754
Probe     2421
U2R        200
Name: classification, dtype: int64

In [15]:
# Check duplicated data
df_train.duplicated().sum()

9

In [16]:
# Drop duplicated data
df_train.drop_duplicates(inplace = True)

# Check for any duplicated values
df_train.duplicated().sum().any()

False

In [17]:
# Check duplicated data
df_test.duplicated().sum()

3

In [18]:
# Drop duplicated data
df_test.drop_duplicates(inplace = True)

# Check for any duplicated values
df_test.duplicated().sum().any()

False

In [19]:
# print number of NaN Values
df_train.isnull().sum().sum().any()

False

In [20]:
# print number of NaN Values
df_test.isnull().sum().sum().any()

False

In [21]:
df_train.to_csv('Clean_KDDTrain.csv', index = False)
df_test.to_csv('Clean_KDDTest.csv', index = False)

In [22]:
# independant and dependant variables
X_train = df_train.iloc[:,:-1].values # independent variables
y_train = df_train.iloc[:,-1].values # dependent variable

In [23]:
# independant and dependant variables
X_test = df_test.iloc[:,:-1].values # independent variables
y_test = df_test.iloc[:,-1].values # dependent variable

In [24]:
print(X_train.shape)

(125964, 41)


In [25]:
print(X_test.shape)

(22541, 41)


In [26]:
# y_train[y_train != 'normal'] = 'anomaly'

In [27]:
# Check whether the dataset is equally splitted or not
from collections import Counter
print(y_train) 
print(Counter(y_train))

['normal' 'normal' 'Dos' ... 'normal' 'Dos' 'normal']
Counter({'normal': 67343, 'Dos': 45927, 'Probe': 11647, 'R2L': 995, 'U2R': 52})


In [28]:
# y_test[y_test != 'normal'] = 'anomaly'

In [29]:
print(y_test) 
print(Counter(y_test))

['Dos' 'Dos' 'normal' ... 'Dos' 'normal' 'Probe']
Counter({'normal': 9711, 'Dos': 7458, 'R2L': 2754, 'Probe': 2418, 'U2R': 200})


In [30]:
# # Encoding indepedant variables
# from sklearn.preprocessing import LabelEncoder
# le_y = LabelEncoder() # LabelEncoder for 1-d array

In [31]:
# y_train = le_y.fit_transform(y_train) # does the same what fit() and transform do in one step
# print(y_train) 

In [32]:
# y_test = le_y.fit_transform(y_test) # does the same what fit() and transform do in one step
# print(y_test)

In [33]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
X_le = LabelEncoder()
X_train[:,1] = X_le.fit_transform(X_train[:,1])
X_train[:,2] = X_le.fit_transform(X_train[:,2])
X_train[:,3] = X_le.fit_transform(X_train[:,3])

In [34]:
X_test[:,1] = X_le.fit_transform(X_test[:,1])
X_test[:,2] = X_le.fit_transform(X_test[:,2])
X_test[:,3] = X_le.fit_transform(X_test[:,3])

In [35]:
print(X_train.shape)

(125964, 41)


In [36]:
print(X_test.shape)

(22541, 41)


In [37]:
print(X_train[:,1:4])

[[1 20 9]
 [2 44 9]
 [1 49 5]
 ...
 [1 54 9]
 [1 30 5]
 [1 20 9]]


In [38]:
print(X_test[:,1:4])

[[1 45 1]
 [1 45 1]
 [1 19 9]
 ...
 [1 22 9]
 [2 11 9]
 [1 52 1]]


In [39]:
# Building SVM classifier
from sklearn.svm import SVC
classifier =  SVC(kernel = 'rbf')

In [40]:
classifier.fit(X_train,y_train)

SVC()

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score,classification_report
acc_score = accuracy_score(y_test, y_pred)
print("Accuracy of Support Vector Machine rbf:",acc_score*100,'\n')
print(classification_report(y_test,y_pred, zero_division = 0))

Accuracy of Support Vector Machine rbf: 43.07262321991038 

              precision    recall  f1-score   support

         Dos       0.00      0.00      0.00      7458
       Probe       0.00      0.00      0.00      2418
         R2L       0.00      0.00      0.00      2754
         U2R       0.00      0.00      0.00       200
      normal       0.43      1.00      0.60      9711

    accuracy                           0.43     22541
   macro avg       0.09      0.20      0.12     22541
weighted avg       0.19      0.43      0.26     22541



In [43]:
indices = np.r_[0, 4,5,9,12,15,16,22,23,31,23]

In [44]:
X_train[:, indices]

array([[0, 491, 0, ..., 2, 150, 2],
       [0, 146, 0, ..., 1, 255, 1],
       [0, 0, 0, ..., 6, 255, 6],
       ...,
       [0, 2231, 384, ..., 1, 255, 1],
       [0, 0, 0, ..., 8, 255, 8],
       [0, 151, 0, ..., 1, 255, 1]], dtype=object)

In [46]:
# Scaling for making close variables values from each other
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

import copy 
X_train_scaling_s = copy.copy(X_train)
X_test_scaling_s = copy.copy(X_test)

# choose [:, indices] for only scaling numerical data
X_train_scaling_s[:, indices] = sc_X.fit_transform(X_train_scaling_s[:, indices]) # apply fit() on X_train and transform fit on X_train 
X_test_scaling_s[:, indices] = sc_X.transform(X_test_scaling_s[:, indices]) # because we already fit() on x_train we only transform fit on X_test

In [47]:
classifier.fit(X_train_scaling_s,y_train)

SVC()

In [48]:
y_pred = classifier.predict(X_test_scaling_s)

In [49]:
from sklearn.metrics import accuracy_score, classification_report
acc_score = accuracy_score(y_test, y_pred)*100
print("Accuracy of Support Vector Machine: {}\n".format(acc_score))
print(classification_report(y_test,y_pred, zero_division = 0))

Accuracy of Support Vector Machine: 64.66882569539949

              precision    recall  f1-score   support

         Dos       0.74      0.64      0.69      7458
       Probe       0.80      0.08      0.14      2418
         R2L       0.00      0.00      0.00      2754
         U2R       0.00      0.00      0.00       200
      normal       0.61      0.99      0.75      9711

    accuracy                           0.65     22541
   macro avg       0.43      0.34      0.32     22541
weighted avg       0.59      0.65      0.57     22541



In [50]:
# Scaling for making close variables values from each other
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

# choose [:, indices] for only scaling numerical data
indices = np.r_[0, 4:41]

import copy 
X_train_scaling = copy.copy(X_train)
X_test_scaling = copy.copy(X_test)

X_train_scaling[:, indices] = sc_X.fit_transform(X_train_scaling[:, indices]) # apply fit() on X_train and transform fit on X_train 
X_test_scaling[:, indices] = sc_X.transform(X_test_scaling[:, indices]) # because we already fit() on x_train we only transform fit on X_test

In [51]:
classifier.fit(X_train_scaling,y_train)

SVC()

In [52]:
y_pred = classifier.predict(X_test_scaling)

In [53]:
from sklearn.metrics import accuracy_score, classification_report
acc_score = accuracy_score(y_test, y_pred)*100
print("Accuracy of Support Vector Machine: {}\n".format(acc_score))
print(classification_report(y_test,y_pred, zero_division = 0))

Accuracy of Support Vector Machine: 72.72525619981367

              precision    recall  f1-score   support

         Dos       0.92      0.74      0.82      7458
       Probe       0.86      0.53      0.65      2418
         R2L       0.96      0.01      0.02      2754
         U2R       0.62      0.08      0.14       200
      normal       0.64      0.98      0.77      9711

    accuracy                           0.73     22541
   macro avg       0.80      0.47      0.48     22541
weighted avg       0.79      0.73      0.68     22541



In [54]:
from sklearn.model_selection import RepeatedStratifiedKFold, GridSearchCV

# don't use this! it is just example for further work
# you can use if you have time at least 4 days and good PC
# parameters = [{'C':[100, 10, 1, 0.1, 0.01], 'gamma' : ['auto', 'scale'],
#                       'kernel': ['poly', 'rbf', 'sigmoid']},
#                      {'C':[100, 10, 1, 0.1, 0.01], 'kernel': ['linear']}]

# use this.......
parameters = [{'C':[10, 1, 0.1], 'gamma' : ['auto', 'scale'],
                    'kernel': ['rbf']}]
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=0)
grid_search= GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = cv, n_jobs = -1)
grid_search = grid_search.fit(X_train_scaling, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("SVM (best score) : ", best_accuracy)
print("best parameters : ", best_parameters)

SVM (best score) :  0.9961496926168846
best parameters :  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
